- type: gameMapPool
  id: WhiteMapPool
  maps:
    - WhiteBagel
    - WhiteBox
    - WhiteCluster
    - WhiteKettle
    - WhiteMarathon
    - WhiteOmega
    - WhitePillar
    - WhiteMoose
    - WhiteOrigin
